# This is a basic workflow to help you get started with Actions

name: build latest image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14.x
      - name: Project setup
        run: yarn install
      - name: Lints and fixes files
        run: yarn lint
      - name: Build sources
        run: |
          yarn build
      - name: Upload Qiniu
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: cn-east-1
          bucket: dianhsu
          dist: dist
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_ACCESS_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SECRET_KEY }}
      - name: Build Docker image
        run: |
          docker build . --tag wustacm/oj-frontend
      - name: Log into Docker Hub Container Registry
        run: |
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
      - name: Publish Image to Docker Hub
        run: |
          docker push wustacm/oj-frontend
